name: Deploy to Vercel
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '>=12.14.1'
    - name: Install dependecies
      run: npm ci
    - name: Build
      run: |
        npm run production
        cat public/mix-manifest.json # see version in log
    - name: Upload compile assets
      uses: actions/upload-artifact@v1
      with:
        name: assets
        path: public
    - name: Deploy to production
      uses: amondnet/vercel-action@v20
      id: vercel-action-production
      if: github.event_name == 'push'
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'